# Plugin developed by xapfeltortexp | www.LostForce.com | Skype: jan_hoeck
# The Y-height! If you fall below this level you lose the round! 
# WARNING!
# Eye height is 1.6 units higher!
#
# Win Money Description:
# If You want that the guy who want should get Money, change use: true
#
# Win Item Description:
# If You want that the guy who want should get Item, change use: true
#
# Feel free to donate to d.hoeck66@gmx.de
OutOfWorld: 5
RunSpeed:
  Speed: 2
  SpeedOverDiamondBlock: 4
BuyPoints:
  HowMuchPoints: 10
  BuyItem: 276
  BuyAmount: 1
Win:
  Money:
    use: false
    Amount: 20
  Item:
    use: true
    Item: 264
    Amount: 1
