# Plugin developed by xapfeltortexp. Do you want to have your own plugin? Then contact me at http://dev.bukkit.org/profiles/xapfeltortexp

TempleRun:
  configVersion: 1.3.0
  # Automatic Update Checker
  Updater:
    checkUpdates: true
  
  Vault:
    # Set this Option to true, if you want, that the Player gets money on win
    usingVault: false
    # Set this to -1 if you dont want, that the Player gets money
    winMoney: 30.40
    
    # If you want, that the Player have to pay for joining Templerun, then set this Option higher then 0
    # Just work, if you have usingVault: true
    joinAmount: -1
  
  Settings:
    # Magnet means the Magnet like in templerun. Set the Time on Seconds:
    magnetBonusTime: 5
  
    # Enable this option, if you want that the walk checker gets enabled.
    # The checker checks, if someone run like in templerun or not.
    enableChecker: true
    # stayTime means, the time your get allowed to stay ( in seconds )
    stayTime: 2
    
    # The Walkspeed in Templerun
    # Can be set from 0.1 until 1.0
    walkSpeed: 0.2
    
    # Set this option to true, if you want that the player
    # get full food and full health when he joins templerun
    updateFoodHealth: false
    
    # How much coins must a player have to save an Checkpoint
    # Example:
    # The Checkpoint should set every 10 Coins. Then write 10 in option
    # Set it to -1 if you dont want to set any checkpoints
    checkpoint: 10
    
    # The block you have to walk over, to "fell out of the world"
    # Use Block-IDs
    # Blocks which can not be used: Emerald, Diamond, Gold
    blocks:
    - 9
    - 10
    
    # All listed commands below, will be useable while playing TempleRun
    allowedCommands:
    - /templerun
    
    # Set this option to true, if you want, that a player automatically leave the arena, when he fails.
    # Like walk over a block you typed in below
    leaveOnFail: false
    
    # Enable this, if you want to broadcast if someone complete a arena
    # %PLAYER = The name of the player
    # %ARENA = The name of the arena
    # %TIME = The time he needed to complete the map
    # %COINS = The gained coins
    broadcastOnWin: true
    broadcastMessage: '&5&l%PLAYER &6completed the TempleRun Map &5%ARENA &6in &5%TIME&6. Gained coins: &5%COINS.'
    
    # If you want that the players in templerun get showed as a ghost, then set this option to true
    ghost: false