name: TempleRun
version: 2.5.3
author: xapfeltortexp
website: www.LostForce.com
dev-url: http://dev.bukkit.org/server-mods/templerun

main: TempleRun.TempleRun

commands:
  templerun:
    description: TempleRun Command
    aliases: tr